# Generated by Django 5.0.7 on 2024-08-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=10)),
                ('zipcode', models.IntegerField()),
                ('phone', models.CharField(default='<PHONE>', max_length=11)),
                ('address', models.CharField(max_length=50)),
                ('detail', models.CharField(max_length=30)),
                ('request', models.CharField(max_length=255)),
            ],
        ),
    ]
