# Generated by Django 5.0.7 on 2024-08-08 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_address_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='request',
        ),
    ]
