# Generated by Django 5.0.3 on 2024-06-04 06:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_productimage_product'),
        ('store', '0005_alter_cart_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(fields=('product', 'customer'), name='unique_cart_product_and_customer'),
        ),
    ]
