# Generated by Django 5.0.3 on 2024-06-04 07:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_productimage_product'),
        ('store', '0006_cart_unique_cart_product_and_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='wishlist',
            constraint=models.UniqueConstraint(fields=('product', 'customer'), name='unique_wishlist_product_and_customer'),
        ),
    ]
