version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - .:/code
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
      - /tmp:/tmp
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
    command: gunicorn config.wsgi.application --bind unix:/tmp/${SOCKET_FILE}.sock
