version: '3'
services:
  nginx:
    image:
      nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/code
      - ./nginx/nginx:/etc/nginx/nginx.conf
    depends_on:
      - test


  test:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn config.wsgi.application --bind unix://tmp/test.sock
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.base

  prod:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn config.wsgi.application --bind unix://tmp/prod.sock
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.prod
