services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    env_file:
      - .env.stage
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - prod
      - stage

  prod:
    container_name: prod
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.prod
    env_file:
      - .env.prod
    command: ["sh", "-c", "poetry run python3 manage.py migrate && poetry run gunicorn --bind 0.0.0.0:8002 config.wsgi:application"]

  stage:
    container_name: stage
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.stage
    env_file:
      - .env.stage
    command: ["sh", "-c", "poetry run python3 manage.py migrate && poetry run gunicorn --bind 0.0.0.0:8001 config.wsgi:application"]
