services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    env_file:
      - nginx.env
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - prod
      - test

  test:
    container_name: test
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.test
    env_file:
      - test.env
    command: ["sh", "-c", "poetry run python3 manage.py migrate && poetry run gunicorn --bind 0.0.0.0:8001 config.wsgi:application"]

  prod:
    container_name: prod
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.prod
    env_file:
      - prod.env
    command: ["sh", "-c", "poetry run python3 manage.py migrate && poetry run gunicorn --bind 0.0.0.0:8002 config.wsgi:application"]
