services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /tmp:/tmp
    depends_on:
      - prod
      - dev

  dev:
    container_name: dev
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.base
    env_file:
      - .env
    command: ["sh", "-c", "poetry run python3 manage.py migrate && poetry run gunicorn --bind 0.0.0.0:8001 config.wsgi:application"]

  prod:
    container_name: prod
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.prod
    env_file:
      - .env
    command: ["sh", "-c", "poetry run python3 manage.py migrate && poetry run gunicorn --bind 0.0.0.0:8002 config.wsgi:application"]
