# Generated by Django 5.0.3 on 2024-05-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img1',
            field=models.URLField(default='https://test-bigbro-bucket.s3.ap-northeast-2.amazonaws.com/images/161764121_342336863872451_1790344446721071304_n.jpg'),
        ),
        migrations.AddField(
            model_name='product',
            name='img2',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='product',
            name='img3',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='product',
            name='img4',
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(choices=[('CBWAS', 'Cbwas'), ('BIGBRO', 'Bigbro'), ('GONGNEW', 'Gongnewgi'), ('SCULFEE', 'Sculfee')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='img5',
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.IntegerField(choices=[(85, 'XS'), (90, 'X'), (95, 'L'), (100, 'XL'), (105, 'XXL'), (110, 'XXXL')]),
        ),
    ]
