# Generated by Django 5.0.3 on 2024-05-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_img1_product_img2_product_img3_product_img4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.IntegerField(choices=[(85, 'XS'), (90, 'X'), (95, 'L'), (100, 'XL'), (105, 'XXL'), (110, 'XXXL')], null=True),
        ),
    ]
