# Generated by Django 5.0.3 on 2024-05-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_rating_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img1',
            field=models.URLField(default='DAC17638-6429-4172-9AB7-35F4313C2394_1_105_c-removebg-preview (2).png'),
        ),
    ]
