# Generated by Django 5.0.3 on 2024-05-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img2',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='img3',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='img4',
            field=models.URLField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='img5',
            field=models.URLField(default=None, null=True),
        ),
    ]
