# Generated by Django 5.0.7 on 2024-07-22 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_discount_product_is_sale_product_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_sale',
            new_name='on_sale',
        ),
    ]
