# Generated by Django 5.0.3 on 2024-06-01 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_category_alter_product_size_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='img',
            new_name='url',
        ),
    ]
