# Generated by Django 5.0.7 on 2024-07-23 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_is_sale_product_on_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('cbw', 'CBWAS'), ('scb', 'S.C.B'), ('big', 'BIGBRO'), ('gon', 'GONGNEWGI'), ('scu', 'SCULFEE')], default='scu', max_length=10),
        ),
    ]
