# Generated by Django 5.0.7 on 2024-07-23 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CBWAS', 'CBWAS'), ('S.C.B', 'S.C.B'), ('BIGBRO', 'BIGBRO'), ('gon', 'GONGNEWGI'), ('scu', 'SCULFEE')], max_length=10),
        ),
    ]
