# Generated by Django 5.0.7 on 2024-07-24 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CBWAS', 'CBWAS'), ('S.C.B', 'S.C.B'), ('BIGBRO', 'BIGBRO'), ('GONGNEWGI', 'GONGNEWGI'), ('SCULFEE', 'SCULFEE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='on_sale',
            field=models.BooleanField(default=True),
        ),
    ]
