# Generated by Django 5.0.7 on 2024-07-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_category_alter_product_on_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CBWAS', 'CBWAS'), ('SCB', 'S.C.B'), ('BIGBRO', 'BIGBRO'), ('GONGNEWGI', 'GONGNEWGI'), ('SCULFEE', 'SCULFEE')], max_length=10),
        ),
    ]
