# Generated by Django 5.0.7 on 2024-07-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='on_sale',
        ),
        migrations.AddField(
            model_name='option',
            name='status',
            field=models.CharField(choices=[('on_sale', 'on_sale'), ('stop_sale', 'stop_sale'), ('sold_out', 'sold_out'), ('discontinued', 'discontinued')], default='on_sale', max_length=15),
        ),
    ]
