# Generated by Django 5.0.3 on 2024-06-03 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_productimage_remove_product_image_product_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='images',
            new_name='image',
        ),
    ]
