# Generated by Django 5.0.3 on 2024-06-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_remove_product_image_productimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='url',
            field=models.CharField(default='DAC17638-6429-4172-9AB7-35F4313C2394_1_105_c-removebg-preview (2).png', max_length=500),
        ),
    ]
