# Generated by Django 5.0.3 on 2024-04-10 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_customer_email_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customer',
            managers=[
            ],
        ),
    ]
