# Generated by Django 5.0.3 on 2024-04-13 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
