# Generated by Django 5.0.3 on 2024-04-17 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
