# Generated by Django 5.0.3 on 2024-05-20 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_delete_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(default='<PHONE>', max_length=11),
        ),
    ]
