# Generated by Django 5.0.3 on 2024-05-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.TextField(default='<URL>'),
        ),
    ]
