# Generated by Django 5.0.3 on 2024-05-21 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_remove_image_image_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(),
        ),
    ]
