# Generated by Django 5.0.7 on 2024-07-15 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=10)),
                ('zipcode', models.IntegerField(max_length=5)),
                ('address', models.CharField(max_length=50)),
                ('detail', models.CharField(max_length=30)),
                ('request', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
