# Generated by Django 5.0.3 on 2024-05-27 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='phone',
        ),
    ]
