# Generated by Django 5.0.7 on 2024-08-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_alter_address_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(default='<PHONE>', max_length=11),
        ),
    ]
