# Generated by Django 5.0.3 on 2024-06-03 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_remove_address_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
