# Generated by Django 5.0.7 on 2024-08-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_remove_address_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.CharField(max_length=6),
        ),
    ]
