# Generated by Django 5.0.7 on 2024-08-09 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_product_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery', models.CharField(max_length=30)),
                ('tracking_number', models.CharField(max_length=30)),
                ('total', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('address_detail', models.CharField(max_length=30)),
                ('zipcode', models.CharField(max_length=30)),
                ('request', models.CharField(max_length=30)),
                ('payment_key', models.CharField(max_length=200)),
                ('order_id', models.CharField(max_length=64)),
                ('total_amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product')),
            ],
        ),
    ]
