# Generated by Django 5.0.7 on 2024-08-16 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_order_id_alter_order_payment_key_and_more'),
        ('product', '0002_product_is_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductItem',
            new_name='OrderItem',
        ),
    ]
