# Generated by Django 5.0.3 on 2024-06-01 11:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_address_alter_order_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c55f5a4b-72f0-413c-9dfd-965e94f34dbc'), editable=False),
        ),
    ]
