# Generated by Django 5.0.7 on 2024-08-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_productitem_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='<NAME>', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
