# Generated by Django 5.0.3 on 2024-06-03 02:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('0cc5d5e2-c630-4083-91e4-19479403f242'), editable=False),
        ),
    ]
