# Generated by Django 5.0.3 on 2024-06-03 03:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('1e79bdf2-1bf6-4832-a995-f80b0b96f3b2'), editable=False),
        ),
    ]
