# Generated by Django 5.0.3 on 2024-06-03 03:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('625d287e-3ef6-4768-81a9-318f8a56753d'), editable=False),
        ),
    ]
