# Generated by Django 5.0.3 on 2024-06-03 03:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('9ea9df51-a6f3-4224-b7c2-fbf5824537c5'), editable=False),
        ),
    ]
