name: CD-test

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - "develop"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          /test/cd.sh

    - name: webhook
      uses: sarisia/actions-status-discord@v1
      if: ${{ success() }}
      with:
        title: test - CI/CD 성공
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        status: ${{ job.status }}
        image: ${{ secrets.SUCCESS_IMAGE }}
        color: 0000CD
        url: "https://github.com/sarisia/actions-status-discord"
        username: Github
    - name: webhook
      uses: sarisia/actions-status-discord@v1
      if: ${{ failure() }}
      with:
        title: CD 실패
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        status: ${{ job.status }}
        image: ${{ secrets.FAILED_IMAGE }}
        color: 00FF00
        url: "https://github.com/sarisia/actions-status-discord"
        username: Github