name: CD

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check
        uses: actions/checkout@v3

      - name: ssh
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/bigbroCO.-Server
            git pull origin develop
            docker stop bigbro-test
            docker rm bigbro-test
            docker build -t bigbro/bigbro-test . 
            docker run -d -it --env-file ./env -p 80:8000 --name bigbro-test bigbro/bigbro-test
