name: CD

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check
        uses: actions/checkout@v3

      - name: ssh
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/bigbroCO.-Server
            git pull origin develop
            sudo docker stop bigbro-test
            sudo docker rm bigbro-test
            ls
            sudo docker build -t bigbro/bigbro-test .
            sudo docker run -d -it --env-file ./.env -p 80:8000 --name bigbro-test bigbro/bigbro-test


      - name: webhook
        uses: sarisia/actions-status-discord@v1
        if: ${{ success() }}
        with:
          title: CD 성공
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          image: ${{ secrets.SUCCESS_IMAGE }}
          color: 0000CD
          url: "https://github.com/sarisia/actions-status-discord"
          username: 작은 아기고양이 재균

      - name: webhook
        uses: sarisia/actions-status-discord@v1
        if: ${{ failure() }}
        with:
          title: CD 실패
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          image: ${{ secrets.FAILED_IMAGE }}
          color: 00FF00
          url: "https://github.com/sarisia/actions-status-discord"
          username: 작은 아기고양이 재균