name: Python3 CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Run Tests
      run: |
        poetry run python manage.py test --settings=config.settings.test

    - name: Python3 CI Success
      uses: sarisia/actions-status-discord@v1
      if: ${{ success() }}
      with:
        title: Python3 Ci Success!
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        status: ${{ job.status }}
        color: 00FF00
        username: GitHub
        url: https://github.com/bigbroCO-team/bigbroCO.-Server

    - name: Python3 CI Fail
      uses: sarisia/actions-status-discord@v1
      if: ${{ failure() }}
      with:
        title: Python3 Ci Fail!
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        status: ${{ job.status }}
        color: FF0000
        username: GitHub
        url: https://github.com/bigbroCO-team/bigbroCO.-Server