name: Compose CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up
      run: |
        sudo apt-get update
        sudo apt-get install docker-compose -y
        
        echo "SECRET_KEY=$SECRET_KEY" >> .env
        echo "ALLOWED_HOSTS=*" >> .env
        echo "DEBUG=1" >> .env

    - name: Build Docker Compose services
      run: docker-compose build
