name: Compose CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up
      run: |
        sudo apt-get update
        sudo apt-get install docker-compose -y
        
        echo "SECRET_KEY=$SECRET_KEY" >> .env
        echo "ALLOWED_HOSTS=*" >> .env
        echo "DEBUG=1" >> .env
    - name: Build Docker Compose services
      run: docker-compose build

    - name: Compose CI Success
      uses: sarisia/actions-status-discord@v1
      if: ${{ success() }}
      with:
        title: Compose Ci Success!
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        status: ${{ job.status }}
        color: 00FF00
        username: GitHub
        url: https://github.com/bigbroCO-team/bigbroCO.-Server

    - name: Compose CI Fail
      uses: sarisia/actions-status-discord@v1
      if: ${{ failure() }}
      with:
        title: Compose Ci Fail!
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        status: ${{ job.status }}
        color: FF0000
        username: GitHub
        url: https://github.com/bigbroCO-team/bigbroCO.-Server