name: Develop CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  python3:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --no-root
    - name: Run Tests
      run: |
        poetry run python manage.py test --settings=config.settings.test

  compose:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up
      run: |
        sudo apt-get update
        sudo apt-get install docker-compose -y
        
        echo "NGINX_TEST_API_DOMAIN=1.1.1.1" >> nginx.env
        echo "NGINX_PROD_API_DOMAIN=1.1.1.1" >> nginx.env
        
        echo "SECRET_KEY=$SECRET_KEY" >> test.env
        echo "ALLOWED_HOSTS=*" >> test.env
        echo "DEBUG=1" >> test.env

        echo "SECRET_KEY=$SECRET_KEY" >> prod.env
        echo "ALLOWED_HOSTS=*" >> prod.env
        echo "DEBUG=1" >> test.env


    - name: Build Docker Compose services
      run: docker-compose build
